# Generated by Django 3.0.6 on 2020-09-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('doctor_type', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
