# Generated by Django 3.0.6 on 2020-09-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uvidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='active',
            new_name='stutas',
        ),
    ]
