# Generated by Django 3.0.5 on 2020-09-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uvidapp', '0002_auto_20200916_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_type',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Ayurvedic', 'Ayurvedic')], max_length=50),
        ),
    ]
