# Generated by Django 3.0.6 on 2020-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uvidapp', '0003_auto_20200916_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jan_Aushadhi_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=500)),
                ('land_agreement', models.ImageField(default='', upload_to='images/')),
                ('aadhar_card', models.ImageField(default='', upload_to='images/')),
                ('status_of_applicant', models.ImageField(default='', upload_to='images/')),
                ('pharmacist_certificate', models.ImageField(default='', upload_to='images/')),
                ('pan_card', models.ImageField(default='', upload_to='images/')),
                ('society_registration_certificate', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
