# Generated by Django 3.0.6 on 2020-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uvidapp', '0004_jan_aushadhi_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jan_aushadhi_registration',
            name='application_form',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
