# Generated by Django 3.0.6 on 2020-09-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uvidapp', '0006_deliverypartner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypartner',
            old_name='driving_icence',
            new_name='driving_licence',
        ),
    ]
