# Generated by Django 3.1 on 2020-09-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uvidapp', '0008_appoitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residing_country', models.CharField(max_length=50)),
                ('residing_state', models.CharField(max_length=50)),
                ('residing_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='appoitement',
            name='Date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='appoitement',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uvidapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uvidapp.state')),
            ],
        ),
    ]
